=== evgenii-sorokin-percent/percent-player/sea-config.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/schemas/node-sea-config.schema.json",
  "title": "Node.js SEA configuration",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "main",
    "output"
  ],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "main": {
      "type": "string",
      "description": "Path to the entry-point JavaScript file."
    },
    "mainFormat": {
      "type": "string",
      "enum": [
        "commonjs",
        "module"
      ],
      "default": "commonjs"
    },
    "executable": {
      "type": "string",
      "description": "Path to the Node.js executable used as the base."
    },
    "output": {
      "type": "string",
      "description": "Path to the generated executable or SEA blob."
    },
    "disableExperimentalSEAWarning": {
      "type": "boolean",
      "default": false
    },
    "useSnapshot": {
      "type": "boolean",
      "default": false
    },
    "useCodeCache": {
      "type": "boolean",
      "default": false
    },
    "execArgv": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "execArgvExtension": {
      "type": "string",
      "enum": [
        "none",
        "env",
        "cli"
      ],
      "default": "env"
    },
    "assets": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}

=== evgenii-sorokin-percent/percent-player/sea-config.json
{
  "$schema": "./sea-config.schema.json",
  "mainFormat": "module",
  "useCodeCache": true,
  "main": "./server/dist/server.js",
  "output": "./dist/percent-player",
  "disableExperimentalSEAWarning": true,
  "executable": "/usr/bin/node",
  "assets": {
    "assets/hero-CLDdwZDr.png": "./client/dist/assets/hero-CLDdwZDr.png",
    "assets/index-D64VDMd1.css": "./client/dist/assets/index-D64VDMd1.css",
    "assets/index-DaeTyWji.js": "./client/dist/assets/index-DaeTyWji.js",
    "assets/react-CHdo91hT.svg": "./client/dist/assets/react-CHdo91hT.svg",
    "assets/vite-BF8QNONU.svg": "./client/dist/assets/vite-BF8QNONU.svg",
    "favicon.svg": "./client/dist/favicon.svg",
    "icons.svg": "./client/dist/icons.svg",
    "index.html": "./client/dist/index.html"
  }
}
